//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.Wizard.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.Wizard.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Specify the age of the person 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Age 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Age 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add dynamic page 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageView_AddDynamicPage {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageView_AddDynamicPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Age 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageView_Age {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageView_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to add a new page to see the dynamic navigation pane behavior? 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageViewModel_AddPageQuestion {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageViewModel_AddPageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add page? 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_AgeWizardPageViewModel_AddPageTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_AgeWizardPageViewModel_AddPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orc.Wizard example 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Common_AppTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Common_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HELP HANDLER 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Common_HelpHandler {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Common_HelpHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Common_SelectAll {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Common_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the components 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Components 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Components selection 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel via code 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_CancelViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_CancelViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the components you want to use: 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move back via code 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_MoveBackViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_MoveBackViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move forward via code 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_MoveForwardViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_MoveForwardViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move next or finish via code 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageView_MoveNextOrFinishViaCode {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageView_MoveNextOrFinishViaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select at least 1 component 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_ComponentsWizardPageViewModel_SelectAtLeast1Component {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_ComponentsWizardPageViewModel_SelectAtLeast1Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the gadgets 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gadgets 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gadgets 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the gadgets you want to use: 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_GadgetsWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_GadgetsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Very long page 1 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long 1 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dictum quam sed suscipit aliquet. Nam malesuada et eros id molestie. Phasellus lacinia eleifend nisi, vitae feugiat turpis laoreet in. Maecenas condimentum commodo metus nec tempor. Suspendisse potenti. Etiam interdum ante vitae est elementum iaculis. Mauris tempor orci ut dolor laoreet malesuada. Morbi tortor sapien, congue nec mauris ac, posuere elementum tortor. Aliquam interdum elementum risus eu egestas. Donec neque ipsum, finibus eget  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph1 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ut egestas lorem nec nisl accumsan fringilla. Maecenas gravida, nisl quis placerat blandit, odio ligula elementum neque, nec accumsan turpis mauris at orci. Vestibulum lorem ipsum, scelerisque eu sodales sit amet, sollicitudin vel dui. In hendrerit nulla a augue vulputate rutrum. Suspendisse facilisis justo id eros imperdiet facilisis. Nullam risus erat, ultricies non vehicula eu, congue et nulla. Pellentesque non laoreet mauris, ut mattis magna. Pellentesque porta efficitur risus, et posuere nisi mollis et [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph2 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Morbi porta lorem sit amet magna varius iaculis. Donec condimentum tortor eu dignissim lobortis. Duis ac sagittis ante, id interdum eros. Suspendisse ultricies felis urna, ac tincidunt sem dapibus sed. In hendrerit mattis urna, non convallis lectus viverra vitae. Vestibulum sit amet ex leo. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac nisi aliquet, congue tellus id, aliquet nibh. Cras vehicula est et urna condimentum pharetra. Integer ex lacus, aliquam id dui lacinia, t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph3 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspendisse potenti. Suspendisse justo lectus, porta in pellentesque et, scelerisque in libero. Nulla posuere felis ut lacus dapibus, ac aliquet tortor tempor. Maecenas feugiat neque eget risus accumsan pharetra. Phasellus sed dolor lacus. Curabitur bibendum lobortis leo eleifend posuere. Phasellus tempus, ante non euismod tincidunt, leo lectus sollicitudin lectus, sed tristique mauris nisl accumsan ligula. Morbi odio velit, vulputate ut leo id, tempus finibus purus. Curabitur vestibulum urna vitae tincidun [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph4 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sed fringilla, mi nec blandit ultricies, tortor nunc consequat sem, nec semper arcu justo vel nisi. Praesent scelerisque mauris eget mauris bibendum, at ultricies nunc dictum. Aliquam faucibus massa vitae sapien sollicitudin, nec dapibus tellus condimentum. Duis interdum elit et velit sollicitudin dictum. Suspendisse elementum mi quis sem molestie, a semper magna ultrices. Sed rutrum magna non metus sodales, eget mattis dui hendrerit. Quisque et nisl vehicula, varius erat facilisis, ullamcorper mauris. Maur [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long1WizardPageView_Paragraph5 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long1WizardPageView_Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Very long page 2 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long 2 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur dictum quam sed suscipit aliquet. Nam malesuada et eros id molestie. Phasellus lacinia eleifend nisi, vitae feugiat turpis laoreet in. Maecenas condimentum commodo metus nec tempor. Suspendisse potenti. Etiam interdum ante vitae est elementum iaculis. Mauris tempor orci ut dolor laoreet malesuada. Morbi tortor sapien, congue nec mauris ac, posuere elementum tortor. Aliquam interdum elementum risus eu egestas. Donec neque ipsum, finibus eget  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph1 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ut egestas lorem nec nisl accumsan fringilla. Maecenas gravida, nisl quis placerat blandit, odio ligula elementum neque, nec accumsan turpis mauris at orci. Vestibulum lorem ipsum, scelerisque eu sodales sit amet, sollicitudin vel dui. In hendrerit nulla a augue vulputate rutrum. Suspendisse facilisis justo id eros imperdiet facilisis. Nullam risus erat, ultricies non vehicula eu, congue et nulla. Pellentesque non laoreet mauris, ut mattis magna. Pellentesque porta efficitur risus, et posuere nisi mollis et [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph2 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Morbi porta lorem sit amet magna varius iaculis. Donec condimentum tortor eu dignissim lobortis. Duis ac sagittis ante, id interdum eros. Suspendisse ultricies felis urna, ac tincidunt sem dapibus sed. In hendrerit mattis urna, non convallis lectus viverra vitae. Vestibulum sit amet ex leo. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac nisi aliquet, congue tellus id, aliquet nibh. Cras vehicula est et urna condimentum pharetra. Integer ex lacus, aliquam id dui lacinia, t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph3 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suspendisse potenti. Suspendisse justo lectus, porta in pellentesque et, scelerisque in libero. Nulla posuere felis ut lacus dapibus, ac aliquet tortor tempor. Maecenas feugiat neque eget risus accumsan pharetra. Phasellus sed dolor lacus. Curabitur bibendum lobortis leo eleifend posuere. Phasellus tempus, ante non euismod tincidunt, leo lectus sollicitudin lectus, sed tristique mauris nisl accumsan ligula. Morbi odio velit, vulputate ut leo id, tempus finibus purus. Curabitur vestibulum urna vitae tincidun [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_Long2WizardPageView_Paragraph4 {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_Long2WizardPageView_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow quick navigation 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AllowQuickNavigation {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AllowQuickNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow quick navigation to visited pages 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AllowQuickNavigationToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AllowQuickNavigationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto size side navigation pane 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AutoSizeSideNavigationPane {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AutoSizeSideNavigationPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto sizing adjusts the spacing between the ellipses in navigation pane so they fit without scrolling. The spacing is calculated from the Wizard window minimum size (MinSize). 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_AutoSizeSideNavigationPaneToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_AutoSizeSideNavigationPaneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache views (do not recreate on each page navigation) 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_CacheViews {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_CacheViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This example will show you how to use the wizard elements in Orc.Wizard. The code is fairly easy to understand. Even though this demo isn&apos;t very meaningful it illustrates the real power of the wizard in combination with Catel:
        ///
        ///- State management (remember values when navigating between views)
        ///- Views can be used inside and outside of the wizard
        ///- Validation per view model or model
        ///- Easy to code, seriously, check it out for yourself! 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle navigation states 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_HandleNavigationStates {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_HandleNavigationStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark all pages as visited before showing wizard 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_MarkAllPagesAsVisited {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_MarkAllPagesAsVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to other screen (if possible) 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_MoveToOtherScreen {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_MoveToOtherScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tests the auto move logic and the page initialization logic. 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_MoveToOtherScreenToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_MoveToOtherScreenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show full screen wizard... 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowFullScreenWizard {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowFullScreenWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show help button 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowHelpButton {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowHelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the help button in the wizard 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowHelpButtonToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowHelpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show in taskbar 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowInTaskbar {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowInTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show an icon in the taskbar for the wizard 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowInTaskbarToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowInTaskbarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show summary page 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowSummaryPage {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowSummaryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the summary page at the end of the wizard. 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowSummaryPageToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowSummaryPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show wizard... 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowWizard {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show wizard with side navigation... 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_ShowWizardWithSideNavigation {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_ShowWizardWithSideNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use fast forward navigation controller 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_UseFastForwardNavigationController {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_UseFastForwardNavigationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The fast forward navigation controller allows to skip pages and go directly to the summary page. Or when there is no summary page, immediately resume from the wizard. 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_MainView_UseFastForwardNavigationControllerToolTip {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_MainView_UseFastForwardNavigationControllerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the details of the person 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Person 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Person 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This wizard page shows you how to map textbox elements to a model and validate them. Notice that you cannot move to the next page while the fields are not yet valid. When navigating forward and back, you will see the values are automatically restored.
        ///
        ///The cool thing is that the view model for this page only has 28 (!) lines of code. This means your pages stay small and are easily maintainable. 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First name 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageView_FirstName {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageView_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last name 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageView_LastName {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageView_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First name is required 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageViewModel_FirstNameRequired {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageViewModel_FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last name is required 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_PersonWizardPageViewModel_LastNameRequired {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_PersonWizardPageViewModel_LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the skills 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPage_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPage_SummaryTitle {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPage_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPage_Title {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select your skills: 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPageView_Description {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select at least 1 skill 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_SkillsWizardPageViewModel_SelectAtLeast1Skill {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SkillsWizardPageViewModel_SelectAtLeast1Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working on it... 的本地化字符串。
        /// </summary>
        internal static string Orc_Wizard_Example_SystemInfoView_WorkingOnIt {
            get {
                return ResourceManager.GetString("Orc_Wizard_Example_SystemInfoView_WorkingOnIt", resourceCulture);
            }
        }
    }
}
